"""Build the n=180 param-scan records WITHOUT re-running the MC.

n=180 is the full default model (CRmat180), whose T3 / bkg_penalty=True
confidence bands are already saved on an energy grid in
    T3/scenario_bkg_{scen}/bands/band_bkg{scen}_idx*_bkgpen.json
(same model, same solver, same penalty — generated by _gen_pen_band.py).

The scan measures the band at TARGET_E using idx = argmin(|eb - E|) with
eb = linspace(0.18, 2, 180). Those exact indices (22, 41, 71) are not on the
saved grid, so we linearly interpolate lower/upper/best_fit in energy between
the two bracketing saved indices. Output schema matches run_param_scan.py.
"""
import os
import glob
import json
import numpy as np

OUTDIR    = 'param_scan_bkgpen'
SCENARIOS = ['a', 'b']
N         = 180
TARGET_E  = [0.40, 0.60, 0.90]
LEVELS    = (0.678, 0.954)
BANDS_DIR = 'T3/scenario_bkg_{scen}/bands'

eb = np.linspace(0.18, 2, N)            # same grid the scan uses for n=180


def load_grid(scen):
    """Return sorted arrays (idx, energy, best_fit, {level:(lo,hi)}) from saved bands."""
    rows = []
    for f in sorted(glob.glob(os.path.join(BANDS_DIR.format(scen=scen),
                                            f'band_bkg{scen}_idx*_bkgpen.json'))):
        b = json.load(open(f))
        i = int(b['index'])
        bp = {}
        for lv in LEVELS:
            key = next(k for k in b['band_physical'] if abs(float(k) - lv) < 1e-6)
            bp[lv] = tuple(b['band_physical'][key])
        rows.append((i, eb[i], float(b['best_fit_physical']), bp))
    rows.sort()
    return rows


def interp_at(rows, E, level):
    """Linear interp of (lower, upper, best_fit) at energy E from the saved grid."""
    xs = np.array([r[1] for r in rows])
    lo = np.array([r[3][level][0] for r in rows])
    hi = np.array([r[3][level][1] for r in rows])
    bf = np.array([r[2] for r in rows])
    return (float(np.interp(E, xs, lo)),
            float(np.interp(E, xs, hi)),
            float(np.interp(E, xs, bf)))


records = []
print(f"{'scen':>4} {'E_target':>8} {'idx':>4} {'E=eb[idx]':>9} {'level':>6} "
      f"{'lower':>14} {'upper':>14} {'width':>14}")
for scen in SCENARIOS:
    rows = load_grid(scen)
    grid_idx = [r[0] for r in rows]
    for E in TARGET_E:
        idx = int(np.argmin(np.abs(eb - E)))
        Ei = float(eb[idx])
        for lv in LEVELS:
            lo, hi, bf = interp_at(rows, Ei, lv)
            records.append(dict(
                scenario=scen, n=int(N), target_E=float(E),
                idx=idx, E=Ei, level=float(lv),
                lower=lo, upper=hi, width=float(hi - lo),
                best_fit=bf, bkg_penalty=True))
            print(f"{scen:>4} {E:>8.2f} {idx:>4} {Ei:>9.4f} {lv:>6.3f} "
                  f"{lo:>14.4e} {hi:>14.4e} {hi - lo:>14.4e}")
    print(f"  [grid idx for {scen}: {grid_idx}]")

out = os.path.join(OUTDIR, 'param_scan_results_nNum.json')
with open(out, 'w') as f:
    json.dump(records, f, indent=1)
print(f"\nWROTE {out}  records={len(records)}")
