"""Generate the numbered tutorial notebooks (run once, then it can be deleted).

Each notebook is a small, self-contained lesson. They share the bundled
``neutrino_analysis_band.py`` and the data folders next to this file, so the
tutorial folder runs on its own.
"""
import json

NBV = 4


def md(*lines):
    return {"cell_type": "markdown", "metadata": {}, "source": _src(lines)}


def code(*lines):
    return {"cell_type": "code", "metadata": {}, "execution_count": None,
            "outputs": [], "source": _src(lines)}


def _src(lines):
    # join with newlines; keep as a single string (valid nbformat source)
    text = "\n".join(lines)
    return text


def notebook(cells):
    return {
        "cells": cells,
        "metadata": {
            "kernelspec": {"display_name": "Python 3", "language": "python",
                           "name": "python3"},
            "language_info": {"name": "python", "version": "3.12"},
        },
        "nbformat": NBV, "nbformat_minor": 5,
    }


def write(name, cells):
    with open(name, "w") as f:
        json.dump(notebook(cells), f, indent=1, ensure_ascii=False)
        f.write("\n")
    print("wrote", name)


# ---------------------------------------------------------------- 00 setup
write("00_setup.ipynb", [
    md("# 00 · Setup & orientation",
       "",
       "This tutorial teaches the `neutrino_analysis_band` API end to end.",
       "The folder is self-contained: the module and the data (`CRmat/`,",
       "`Ratebin/`, `Danny's files/`) live right here, so run the notebooks",
       "with this `tutorial/` folder as the working directory.",
       "",
       "Lessons:",
       "",
       "- **00** setup & orientation (this file)",
       "- **01** optimize the flux and plot it",
       "- **02** the two solver backends (`scipy` / `osqp`) and the staircase",
       "- **03** Δχ² scan on a fixed parameter",
       "- **04** confidence band by root finding",
       "- **05** save bands per index and overlay on the flux",
       "- **06** compare scenarios on one axis",
       "- **07** vary the observation time `T` (output foldering)",
       "- **08** pitfalls & troubleshooting"),
    md("## Dependencies",
       "",
       "Core: `numpy scipy matplotlib pandas numba`.  ",
       "For `solver='osqp'`: `cvxpy osqp` (and optionally `highspy` for the",
       "fastest staircase solver — SciPy's bundled LP is used otherwise)."),
    code("import warnings",
         "warnings.simplefilter('ignore')   # quiet solver 'inaccurate' notices",
         "",
         "from neutrino_analysis_band import NeutrinoAnalysis, load_band",
         "import numpy as np",
         "import cvxpy as cp",
         "",
         "print('cvxpy solvers available:', cp.installed_solvers())",
         "# 'SCIPY' guarantees the staircase even without HiGHS"),
    code("# Construct an analysis object. Arguments you will reuse throughout:",
         "#   background_scenario : 'a' / 'b' / 'b2' / 'c' / 'flat' / 'none'",
         "#   intervals           : response-matrix granularity (here '180')",
         "#   GeV                 : natural-unit scale (0.3-0.6e16 is well-conditioned)",
         "#   solver              : 'scipy' (stable) or 'osqp' (fast)",
         "#   T                   : observation time; sets output folder T<T>/",
         "a = NeutrinoAnalysis(background_scenario='flat', intervals='180',",
         "                     GeV=0.32e16, solver='scipy', T=3)",
         "print('bins (m) =', a.m, ' flux params (n) =', a.n)",
         "print('output dir   :', a.scenario_dir)",
         "print('bands dir    :', a.bands_dir)"),
])

# ---------------------------------------------------------------- 01 optimize
write("01_optimize_and_plot.ipynb", [
    md("# 01 · Optimize the flux and plot it",
       "",
       "`optimize(data)` minimizes χ². It returns a result with `.x` (the flux",
       "vector), `.fun` (χ², in scaled units — divide by `a.c` for χ²/c), and",
       "`.success`. It also stores the result on `a.result`, which the plotting",
       "and band routines reuse."),
    code("import warnings; warnings.simplefilter('ignore')",
         "from neutrino_analysis_band import NeutrinoAnalysis",
         "import numpy as np",
         "",
         "a = NeutrinoAnalysis(background_scenario='flat', intervals='180',",
         "                     GeV=0.32e16, solver='scipy', T=3)",
         "res = a.optimize(a.data_vector)",
         "print('success :', res.success)",
         "print('chi2/c  :', res.fun / a.c)"),
    code("# Flux is monotonically non-increasing (an ordering constraint).",
         "x = res.x",
         "print('first 6 flux values :', np.round(x[:6], 3))",
         "print('monotone non-incr   :', bool(np.all(np.diff(x) <= 1e-6 * np.abs(x).max())))",
         "",
         "# Convert to physical units (cm^-2 s^-1):",
         "phys = x * (a.cm**2 * a.sec)",
         "print('flux[0] physical    : %.3e' % phys[0])"),
    code("# Plot optimized flux against the theoretical curves.",
         "# save=True writes T3/scenario_bkg_flat/flux_comparison_bkg_flat.pdf",
         "a.plot_flux_comparison(save=True)",
         "import matplotlib.pyplot as plt; plt.show()"),
    md("**Try it:** change `background_scenario` to `'a'` or `'b'` and re-run.",
       "The optimized χ²/c stays ~0 (the fit is exact) but the flux shape shifts."),
])

# ---------------------------------------------------------------- 02 solvers
write("02_solvers_and_staircase.ipynb", [
    md("# 02 · Solver backends and the staircase",
       "",
       "Two backends solve the same χ² problem:",
       "",
       "- `scipy` — `trust-constr`, stable, the safe default.",
       "- `osqp` — formulates χ² as a QP; fast. For this under-determined",
       "  problem (180 params, 29 bins) it additionally runs a **simplex LP** to",
       "  pick a *vertex* — a piecewise-constant (staircase) flux.",
       "",
       "Both report the same χ². The flux *shape* can differ because the optimum",
       "is a whole face, not a point."),
    code("import warnings; warnings.simplefilter('ignore')",
         "from neutrino_analysis_band import NeutrinoAnalysis",
         "import numpy as np",
         "",
         "def flat_pairs(x, tol=1e-5):",
         "    d = np.abs(np.diff(x))",
         "    return int(np.sum(d <= tol * np.abs(x).max()))",
         "",
         "a = NeutrinoAnalysis(background_scenario='flat', intervals='180',",
         "                     GeV=0.32e16, solver='scipy', T=3)",
         "xs = a.optimize(a.data_vector).x",
         "print('scipy : chi2/c=%.2e  flat-adjacent pairs=%d/%d'",
         "      % (a.result.fun / a.c, flat_pairs(xs), a.n - 1))"),
    code("# Switch to OSQP on the same object.",
         "a.set_solver('osqp')",
         "xo = a.optimize(a.data_vector).x",
         "print('osqp  : chi2/c=%.2e  flat-adjacent pairs=%d/%d'",
         "      % (a.result.fun / a.c, flat_pairs(xo), a.n - 1))",
         "print('osqp staircase? (many flat pairs ->) ', flat_pairs(xo) > 100)"),
    code("# Sanity: the returned flux really achieves the reported chi2.",
         "d, b, M = a.data_vector, a.Bkg_vector, a.M_matrix",
         "resid = (d - b) - M @ xo",
         "inv = np.where(d > 0, 1 / np.where(d > 0, d, 1), 0)",
         "chi2_hand = a.T * np.sum(resid * resid * inv) / a.c",
         "print('reported chi2/c = %.3e' % (a.result.fun / a.c))",
         "print('hand-computed   = %.3e' % chi2_hand)"),
    md("**Vertex selection** is controlled by `a._backend.vertex_select`",
       "(default `True`). Set it to `False` to get the smooth interior solution.",
       "The staircase needs a simplex LP solver; the code tries HiGHS → GLPK →",
       "SciPy, and SciPy ships with cvxpy, so it works out of the box."),
])

# ---------------------------------------------------------------- 03 scan
write("03_chi2_scan.ipynb", [
    md("# 03 · Δχ² scan on a fixed parameter",
       "",
       "`scan_fixed_parameter` walks one flux component across a grid, refits with",
       "that component pinned, and runs a Monte-Carlo (Neyman) test at each point",
       "to decide whether the value is inside the 1σ / 90% / 2σ band.",
       "",
       "It returns a list of dicts — drop it straight into a DataFrame."),
    code("import warnings; warnings.simplefilter('ignore')",
         "from neutrino_analysis_band import NeutrinoAnalysis",
         "import pandas as pd",
         "",
         "a = NeutrinoAnalysis(background_scenario='flat', intervals='180',",
         "                     GeV=0.32e16, solver='osqp', T=3)",
         "a.optimize(a.data_vector)   # best fit first; fills a.result",
         "",
         "scan = a.scan_fixed_parameter(",
         "    fixed_index=20, scan_range=0.5, num_points=6,",
         "    num_pseudo_data=20, seed=42, n_jobs=1,",
         ")",
         "df = pd.DataFrame(scan)",
         "df[['fixed_value_physical', 'included1sigma', 'included90',",
         "    'included2sigma', 'delta_chi2_cutoff90']]"),
    md("Columns: `fixed_value_physical` is the pinned flux (cm⁻² s⁻¹);",
       "`includedXX` flags whether it falls inside that level; `delta_chi2_cutoffXX`",
       "is the Monte-Carlo cutoff used. This is the manual-grid approach — lesson",
       "04 finds the band edges directly instead."),
])

# ---------------------------------------------------------------- 04 band
write("04_confidence_band.ipynb", [
    md("# 04 · Confidence band by root finding",
       "",
       "`find_confidence_band` locates the band edges directly: it brackets the",
       "outer reach with the widest level (2σ), then pins each level's edge by",
       "geometric bisection. Far fewer Monte-Carlo evaluations than a dense grid.",
       "",
       "Key knobs (see lesson 08 for tuning):",
       "- `num_pseudo_data` — bracketing sample size (≥50 for 2σ)",
       "- `n_pseudo_edge`   — edge bisection sample size (≥500 to converge)",
       "- `step`            — bracket expansion factor (use 1.5)",
       "- `rel_tol`         — edge resolution",
       "- `seed`            — fix for reproducibility"),
    code("import warnings; warnings.simplefilter('ignore')",
         "from neutrino_analysis_band import NeutrinoAnalysis",
         "",
         "a = NeutrinoAnalysis(background_scenario='flat', intervals='180',",
         "                     GeV=0.32e16, solver='osqp', T=3)",
         "a.optimize(a.data_vector)",
         "",
         "band = a.find_confidence_band(",
         "    fixed_index=20,",
         "    levels=(0.678, 0.90, 0.954),",
         "    num_pseudo_data=30, n_pseudo_edge=120,   # small for a quick demo",
         "    step=1.5, rel_tol=0.05, seed=42, verbose=True,",
         ")"),
    code("# The result is nested: tighter levels sit inside wider ones.",
         "print('best fit (phys) = %.3e' % band['best_fit_physical'])",
         "for lv in band['levels']:",
         "    lo, hi = band['band_physical'][lv]",
         "    print('  %.3f : [%.3e, %.3e]' % (lv, lo, hi))"),
    md("**Note:** with small `n_pseudo_edge` the edges carry Monte-Carlo noise.",
       "Increase it (≥500) for publication numbers — lesson 08 shows the",
       "convergence behaviour."),
])

# ---------------------------------------------------------------- 05 save/overlay
write("05_save_and_overlay.ipynb", [
    md("# 05 · Save bands per index and overlay on the flux",
       "",
       "Compute a band for several indices, save one JSON per index, then overlay",
       "them on the optimized flux as asymmetric error bars."),
    code("import warnings; warnings.simplefilter('ignore')",
         "from neutrino_analysis_band import NeutrinoAnalysis",
         "",
         "a = NeutrinoAnalysis(background_scenario='flat', intervals='180',",
         "                     GeV=0.32e16, solver='osqp', T=3)",
         "a.optimize(a.data_vector)",
         "",
         "# A few indices for a quick demo (real runs use many more).",
         "for idx in [0, 20, 40, 80, 120]:",
         "    a.find_and_save_band(",
         "        idx, levels=(0.678, 0.954),",
         "        num_pseudo_data=20, n_pseudo_edge=80,   # small/fast for the demo",
         "        step=1.5, rel_tol=0.08, seed=42, verbose=False,",
         "    )",
         "print('saved to', a.bands_dir)"),
    code("# Overlay the saved bands on the optimize result.",
         "a.plot_flux_with_bands(f'{a.bands_dir}/band_*.json',",
         "                       levels=(0.678, 0.954), ylim=(0, 3e13))",
         "import matplotlib.pyplot as plt; plt.show()"),
    md("`save_band` / `load_band` use plain JSON (human-readable). The band",
       "centre is the saved `a.result.x[index]`, so it lines up exactly with the",
       "scatter from the same `optimize` result."),
])

# ---------------------------------------------------------------- 06 compare
write("06_scenario_comparison.ipynb", [
    md("# 06 · Compare scenarios on one axis",
       "",
       "`plot_band_comparison` overlays one confidence level from several",
       "scenarios, each in its own colour. Bands are physical units, so they are",
       "comparable across scenarios. `optimized=` adds each scenario's flux",
       "scatter in the matching colour.",
       "",
       "This lesson reuses the bands you saved in lesson 05, plus a second",
       "scenario's bands."),
    code("import warnings; warnings.simplefilter('ignore')",
         "from neutrino_analysis_band import NeutrinoAnalysis",
         "",
         "# Scenario 1: flat (bands from lesson 05). Recompute here so the",
         "# notebook is runnable on its own.",
         "a_flat = NeutrinoAnalysis(background_scenario='flat', intervals='180',",
         "                          GeV=0.32e16, solver='osqp', T=3)",
         "a_flat.optimize(a_flat.data_vector)",
         "for idx in [0, 20, 40, 80, 120]:",
         "    a_flat.find_and_save_band(idx, levels=(0.678, 0.954),",
         "        num_pseudo_data=20, n_pseudo_edge=80, step=1.5, rel_tol=0.08,",
         "        seed=42, verbose=False)",
         "",
         "# Scenario 2: background 'a'.",
         "a_a = NeutrinoAnalysis(background_scenario='a', intervals='180',",
         "                       GeV=0.32e16, solver='osqp', T=3)",
         "a_a.optimize(a_a.data_vector)",
         "for idx in [0, 20, 40, 80, 120]:",
         "    a_a.find_and_save_band(idx, levels=(0.678, 0.954),",
         "        num_pseudo_data=20, n_pseudo_edge=80, step=1.5, rel_tol=0.08,",
         "        seed=42, verbose=False)"),
    code("a_flat.plot_band_comparison(",
         "    {'flat': f'{a_flat.bands_dir}/band_*.json',",
         "     'a':    f'{a_a.bands_dir}/band_*.json'},",
         "    level=0.954,",
         "    optimized={'flat': a_flat, 'a': a_a},",
         "    ylim=(0, 3e13), save=True,",
         ")",
         "import matplotlib.pyplot as plt; plt.show()"),
    md("Labels in `groups` and `optimized` should match so the band and its",
       "scatter share a colour. Differences smaller than `rel_tol` are not",
       "physical — see lesson 08."),
])

# ---------------------------------------------------------------- 07 T
write("07_varying_T.ipynb", [
    md("# 07 · Varying the observation time `T`",
       "",
       "`T` is a constructor argument (default 3). It scales the statistics and,",
       "for bookkeeping, prefixes every output path with `T<T>/`, so different",
       "`T` runs never overwrite each other."),
    code("import warnings; warnings.simplefilter('ignore')",
         "from neutrino_analysis_band import NeutrinoAnalysis",
         "",
         "for T in (3, 30, 300):",
         "    a = NeutrinoAnalysis(background_scenario='flat', intervals='180',",
         "                         GeV=0.32e16, solver='osqp', T=T)",
         "    print('T=%-3d  scenario_dir=%-26s bands_dir=%s'",
         "          % (T, a.scenario_dir, a.bands_dir))"),
    md("Larger `T` gives **narrower** bands (more statistics). Because the bands",
       "shrink, numerical precision matters more: prefer a well-conditioned",
       "`GeV` (~0.3-0.6e16) and a large `n_pseudo_edge`. Lesson 08 covers this."),
    code("# Quick illustration: best fit is the same, but compare T's later via",
         "# find_confidence_band with a large n_pseudo_edge. Here just confirm the",
         "# objects build and the output paths differ.",
         "import os",
         "a = NeutrinoAnalysis(background_scenario='flat', intervals='180',",
         "                     GeV=0.32e16, solver='osqp', T=30)",
         "a.optimize(a.data_vector)",
         "a.plot_flux_comparison(save=True)   # writes under T30/",
         "print('exists:', os.path.exists(a.scenario_dir))"),
])

# ---------------------------------------------------------------- 08 pitfalls
write("08_pitfalls_and_troubleshooting.ipynb", [
    md("# 08 · Pitfalls & troubleshooting",
       "",
       "The lessons above used small Monte-Carlo sizes for speed. Here is what to",
       "watch for in real runs."),
    md("## 1. No staircase (smooth ramp instead)",
       "",
       "Vertex selection needs a simplex LP solver. If none is installed the flux",
       "falls back to the smooth interior solution. Check:"),
    code("import cvxpy as cp",
         "print('installed:', cp.installed_solvers())",
         "print('has a simplex solver:', any(s in cp.installed_solvers()",
         "                                   for s in ('HIGHS', 'GLPK', 'SCIPY')))",
         "# 'SCIPY' is bundled, so this is normally True. `pip install highspy`",
         "# adds the faster HiGHS."),
    md("## 2. `GeV` affects OSQP precision",
       "",
       "The physical flux is GeV-invariant, but OSQP's *relative* accuracy",
       "degrades as `GeV` grows. Smaller, well-conditioned `GeV` gives a much",
       "smaller χ²/c."),
    code("import warnings; warnings.simplefilter('ignore')",
         "from neutrino_analysis_band import NeutrinoAnalysis",
         "import numpy as np",
         "for GeV in (0.32e16, 1e16, 2e16):",
         "    a = NeutrinoAnalysis(background_scenario='flat', intervals='180',",
         "                         GeV=GeV, solver='osqp', T=3)",
         "    r = a.optimize(a.data_vector)",
         "    d, b, M = a.data_vector, a.Bkg_vector, a.M_matrix",
         "    resid = (d - b) - M @ r.x",
         "    inv = np.where(d > 0, 1 / np.where(d > 0, d, 1), 0)",
         "    hand = a.T * np.sum(resid * resid * inv) / a.c",
         "    print('GeV=%.2e : chi2/c=%.2e (flux[0] phys=%.3e)'",
         "          % (GeV, hand, r.x[0] * (a.cm**2 * a.sec)))"),
    md("## 3. Edge returns `inf`",
       "",
       "`step` too small can't reach a far upper edge (reach ≈ `v0·step^25`).",
       "Use `step=1.5`. A too-small `step` like 1.05 only reaches ~3.4× v0."),
    md("## 4. Jagged / non-monotonic bands at large `T`",
       "",
       "Narrow bands amplify any numerical error. Use a well-conditioned `GeV`,",
       "a large `n_pseudo_edge` (≥500), and regenerate stale band files.",
       "",
       "## 5. Sub-`rel_tol` differences are not physical",
       "",
       "Two edges closer than `rel_tol` (their resolution) are *equal*. To claim",
       "a scenario difference, report edge ± uncertainty over a **seed ensemble**",
       "and show the difference exceeds it. For weakly-constrained upper edges,",
       "report a **one-sided limit** instead of chasing precision."),
])

print("done")
